matrix:
  fast_finish: true
  include:
    - os: osx
      env:
        - OS_TYPE=OSX
language: cpp
env:
  global:
    - CXXFLAGS=-gsplit-dwarf
before_install:
  - |
    if [ x"$OS_TYPE" = x"OSX" ]
    then
      brew tap caskroom/cask
      brew install python brew-cask
      brew link --overwrite python
      brew cask install java
    fi
before_script:
  - |
    if [ x"$OS_TYPE" = x"OSX" ]
    then
      export JAVA_HOME=$(/usr/libexec/java_home)
    fi
  - ./bootstrap
  - mkdir build
  - cd build
script:
  - ../configure
  - make -j2 check
