matrix:
  fast_finish: true
  include:
    - os: linux
      env: BUILD_TYPE=Debug
      compiler: clang
    - os: linux
      env: BUILD_TYPE=Release
      compiler: clang
    - os: linux
      env: BUILD_TYPE=Debug
      compiler: gcc
    - os: linux
      env: BUILD_TYPE=Release
      compiler: gcc
language: cpp
before_install:
  - lscpu
  - add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - apt-get update -qq
  - apt-get install -y libapr1-dev libsvn-dev libsasl2-dev libstdc++-4.8-dev gcc-4.8
  - apt-get install -y libapr1-dev libsvn-dev libsasl2-dev
before_script:
  - ./bootstrap
  - mkdir build
  - cd build
script:
  - if [ "$BUILD_TYPE" = "Debug" ]; then ../configure --enable-debug; fi
  - if [ "$BUILD_TYPE" = "Release" ]; then ../configure; fi
  - make -j4
  - cd src && make check
